const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/wabba/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{fs.mkdirSync('test-artifacts',{recursive:true});const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));let requests=[];page.on('request',r=>requests.push(r.url()));
const url=process.env.TEST_URL||'file:///'+path.resolve('prototypes/m1/index.html').replaceAll('\\','/');await page.goto(url);await page.screenshot({path:'test-artifacts/start.png'});await page.getByRole('button',{name:'Begin field test'}).click();await page.keyboard.down('Space');await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>abductTest.field.link?.id),'cow');await page.keyboard.down('w');await page.waitForTimeout(1000);await page.keyboard.up('w');assert(await page.evaluate(()=>abductTest.field.u.y<400));await page.keyboard.up('Space');await page.waitForTimeout(50);assert.equal(await page.evaluate(()=>abductTest.field.link),null);
await page.keyboard.down('Space');await page.evaluate(()=>window.dispatchEvent(new Event('blur')));assert.equal(await page.evaluate(()=>abductTest.mode),'pause');assert.equal(await page.evaluate(()=>abductTest.keys.length),0);const paused=await page.evaluate(()=>abductTest.field.time);await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>abductTest.field.time),paused);await page.keyboard.up('Space');await page.getByRole('button',{name:'Resume flight'}).click();
await page.keyboard.press('r');await page.keyboard.press('F3');await page.screenshot({path:'test-artifacts/play.png'});
// Complete the actual simulation route inside the browser with continuous force input.
await page.evaluate(()=>{const f=abductTest.field;for(let i=0;i<4800&&!f.won;i++){let tx=190,ty=300;if(f.time>5){tx=1040;ty=300}if(f.time>14){tx=1040;ty=435}const u=f.u;f.step({x:Math.max(-1,Math.min(1,((tx-u.x)*3-u.vx*3)/500)),y:Math.max(-1,Math.min(1,((ty-u.y)*5-u.vy*4-(f.link?520/4.5:0))/500)),beam:f.time<23})}});await page.waitForTimeout(60);assert.equal(await page.evaluate(()=>abductTest.mode),'result');await page.screenshot({path:'test-artifacts/result.png'});await page.getByRole('button',{name:'Fly again'}).click();assert.equal(await page.evaluate(()=>abductTest.field.score),0);
for(let i=0;i<10;i++)await page.keyboard.press('r');assert.equal(await page.evaluate(()=>abductTest.mode),'play');
// Toggle mode, local reset, storage failure fallback, narrow layout.
await page.locator('#toggle').check();await page.locator('canvas').click({position:{x:10,y:10}});await page.keyboard.press('Space');await page.waitForTimeout(60);assert(await page.evaluate(()=>!!abductTest.field.link));await page.keyboard.press('Space');await page.waitForTimeout(60);assert.equal(await page.evaluate(()=>abductTest.field.link),null);await page.locator('#reset').click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('abduct-m1.1')).record),null);
const perf=await page.evaluate(()=>new Promise(resolve=>{const intervals=[];let last=performance.now();function tick(t){intervals.push(t-last);last=t;if(intervals.length<120)requestAnimationFrame(tick);else resolve({average:intervals.slice(1).reduce((a,b)=>a+b,0)/119,max:Math.max(...intervals.slice(1))})}requestAnimationFrame(tick)}));
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-artifacts/mobile.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=390));const offline=await browser.newPage();await offline.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new Error('denied')}})});await offline.goto(url);await offline.getByRole('button',{name:'Begin field test'}).click();assert.equal(await offline.evaluate(()=>abductTest.mode),'play');assert.equal(errors.length,0);if(url.startsWith('file:'))assert(requests.every(r=>r.startsWith('file:')));
console.log(JSON.stringify({browser:await browser.version(),viewport:'1440x1000 / 390x844',url,errors,requests,frameIntervalsMs:perf,checks:'offline, keyboard attach/lift/release, focus pause, route/result/retry, rapid reset, toggle, local reset, denied storage, mobile layout'},null,2));await browser.close()})().catch(e=>{console.error(e);process.exitCode=1});
