const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/wabba/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {pilot,MISSIONS}=require('./campaign.cjs');const assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--no-sandbox']});try{
const page=await browser.newPage({viewport:{width:1440,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const url=process.env.TEST_URL||'file:///'+path.resolve('prototypes/m1/index.html').replaceAll('\\','/');await page.goto(url);await page.getByRole('button',{name:'Contracts',exact:true}).click();assert.equal(await page.locator('.job').count(),13);assert(await page.locator('[data-mission="6"]').isDisabled());assert(await page.locator('[data-ship="atlas"]').isDisabled());await page.screenshot({path:'test-artifacts/nightfall-fresh-board.png'});
// Legacy completion migration is a controlled save fixture; missions are not marked won by tests.
await page.evaluate(ids=>{localStorage.removeItem('abduct-nightfall-2');localStorage.setItem('abduct-campaign-1',JSON.stringify(Object.fromEntries(ids.map(id=>[id,{time:60,stars:2}]))));},MISSIONS.slice(0,6).map(m=>m.id));await page.reload();await page.getByRole('button',{name:'Contracts',exact:true}).click();assert((await page.locator('#progress').textContent()).includes('6/12'));assert(!(await page.locator('[data-ship="atlas"]').isDisabled()));await page.locator('[data-ship="swift"]').click();assert((await page.locator('[data-ship="swift"]').textContent()).includes('EQUIPPED'));await page.locator('[data-mission="0"]').click();await page.getByRole('button',{name:'Launch contract'}).click();assert.equal(await page.evaluate(()=>abductTest.field.shipId),'swift');
await page.getByRole('button',{name:'Contracts',exact:true}).click();await page.locator('[data-ship="courier"]').click();await page.screenshot({path:'test-artifacts/nightfall-hangar.png'});
for(let mission=6;mission<12;mission++){
 if(mission>6)await page.getByRole('button',{name:'Contracts',exact:true}).click();await page.locator(`[data-mission="${mission}"]`).click();await page.getByRole('button',{name:'Launch contract'}).click();if(mission===7)assert.equal(await page.evaluate(()=>abductTest.field.shipId),'atlas');
 if(mission===9)await page.screenshot({path:'test-artifacts/nightfall-defenses.png'});
 await page.evaluate(source=>{const control=eval('('+source+')')(),f=abductTest.field;for(let k=0;k<36000&&!f.won&&!f.failed;k++)f.step(control(f));},pilot.toString());await page.waitForTimeout(50);
 const r=await page.evaluate(()=>({name:abductTest.field.mission.name,won:abductTest.field.won,mode:abductTest.mode,damage:abductTest.field.damage,ship:abductTest.field.shipId}));console.log(r);assert(r.won);assert.equal(r.mode,'result');
}await page.screenshot({path:'test-artifacts/nightfall-finale.png'});await page.reload();await page.getByRole('button',{name:'Contracts',exact:true}).click();assert((await page.locator('#progress').textContent()).includes('12/12'));
await page.locator('[data-mission="6"]').click();await page.getByRole('button',{name:'Launch contract'}).click();await page.evaluate(()=>{const f=abductTest.field;for(let i=0;i<3;i++){f.invulnerable=0;f.hit();}});await page.waitForTimeout(40);assert.equal(await page.evaluate(()=>abductTest.mode),'failure');await page.screenshot({path:'test-artifacts/nightfall-failure.png'});await page.getByRole('button',{name:'Retry contract'}).click();assert.equal(await page.evaluate(()=>abductTest.field.shields),3);assert.equal(await page.evaluate(()=>abductTest.mode),'play');
await page.getByRole('button',{name:'Contracts',exact:true}).click();await page.getByRole('button',{name:'Back',exact:true}).click();await page.locator('#reset').click();await page.reload();await page.getByRole('button',{name:'Contracts',exact:true}).click();assert((await page.locator('#progress').textContent()).includes('0/12'));assert(await page.locator('[data-ship="atlas"]').isDisabled());
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-artifacts/nightfall-mobile.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=390));assert.equal(errors.length,0);console.log('PASS: locks, migration, equipped ships, six new routes, scoped records, failure/retry, reset persistence, mobile, no errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
